Changed control scheme...
raubana/AttackOfTheMimics pull request #1
Opened 2017-08-12 06:26 UTC by FusionLord

- Changed controls;
- Merged mimic weapons;
- Moved scream to reload;
- Optimised some code;
- Removed temporary scream drawing;
- Added status bar for screaming;
- Removed unused swep;

2017-08-12 10:51 UTC, raubana requested changes
I'll gladly merge after these minor details are addressed.

2017-08-12 10:51 UTC, raubana commented on gamemodes/attack_of_the_mimics/entities/weapons/swep_aotm_claws.lua
> +		self:EmitSound( table.Random(self.Primary.HitSound) )
This was mentioned in the wiki to be less efficient. https://wiki.garrysmod.com/page/table/Random

2017-08-12 10:51 UTC, raubana commented on gamemodes/attack_of_the_mimics/entities/weapons/swep_aotm_claws.lua
> +		self.Owner:EmitSound( table.Random(self.Scream.Sounds), 95, Lerp(math.random(), 80, 100) )
Again, this was mentioned in the wiki to be less efficient. https://wiki.garrysmod.com/page/table/Random

2017-08-12 10:51 UTC, raubana commented on gamemodes/attack_of_the_mimics/gamemode/cl_init.lua
> +			scream_cooldown = (CurTime() - (localplayer:GetActiveWeapon().scream_init or 0)) / localplayer:GetActiveWeapon().Scream.Delay;
Should be a local variable. This might become global otherwise.

2017-08-12 10:54 UTC, raubana approved these changes

2017-08-12 10:54 UTC, raubana commented
Oops.

2017-08-12 10:55 UTC, raubana commented
I didn't mean to do that. I'm going to add in those requests again.

2017-08-12 10:56 UTC, raubana requested changes
Ok, there we go. Once these are addressed I'll merge.

2017-08-12 10:56 UTC, raubana commented on gamemodes/attack_of_the_mimics/entities/weapons/swep_aotm_claws.lua
> +		self:EmitSound( table.Random(self.Primary.HitSound) )
This was mentioned in the wiki to be less efficient. https://wiki.garrysmod.com/page/table/Random

2017-08-12 10:56 UTC, raubana commented on gamemodes/attack_of_the_mimics/entities/weapons/swep_aotm_claws.lua
> +		self.Owner:EmitSound( table.Random(self.Scream.Sounds), 95, Lerp(math.random(), 80, 100) )
This was mentioned in the wiki to be less efficient. https://wiki.garrysmod.com/page/table/Random

2017-08-12 10:56 UTC, raubana commented on gamemodes/attack_of_the_mimics/gamemode/cl_init.lua
> +			scream_cooldown = (CurTime() - (localplayer:GetActiveWeapon().scream_init or 0)) / localplayer:GetActiveWeapon().Scream.Delay;
Should be a local variable. This might become global otherwise.

2017-08-12 23:46 UTC, FusionLord commented
All requested changes have been made.

2017-08-13 00:42 UTC, raubana reviewed
Merged. Thank you.

2017-08-13 00:42 UTC, raubana approved these changes

2017-08-13 00:42 UTC, merged